POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJleHAiOjE3NTM4MjE5NzQsInVzZXJJZCI6MX0.ww2Sma1BiK8nyR8WK9BflK0FAk0_RVhNZ4Q3lcTo3Vk

{
    "name":"ReactJs 19.",
    "description":"React Evt.",
    "location":"Kolkata, IN",
    "dateTime":"2025-07-01T15:30:00.000Z"

}